# Site settings
title: Learn Mirobot
collections:
  docs:
    output: true
    permalink: /docs/:path/
exclude:
 - Gemfile
 - Gemfile.lock
 - s3_website.yml
 - README.md
 - bin
 - vendor

# Build settings
markdown: kramdown
