# Site settings
title: Learn Mirobot
collections:
  docs:
    output: true
    permalink: /docs/:path/
exclude:
 - Gemfile
 - Gemfile.lock
 - s3_website.yml
 - README.md
 - bin
 - vendor
plugins:
 - jekyll-assets
assets:
  compress:
    css: false
    js: false
  prefix: "/assets"
  digest: true
  sources:
    - _assets/js
    - _assets/css
